title    Arch Linux install medium (%ARCH%, UEFI) with speech
sort-key 02
linux    /%INSTALL_DIR%/boot/%ARCH%/vmlinuz-6.12-x86_64
initrd   /%INSTALL_DIR%/boot/%ARCH%/initramfs-6.12-x86_64.img
options  archisobasedir=%INSTALL_DIR% archisosearchuuid=%ARCHISO_UUID% accessibility=on
